### PR TITLE
Leah Firestone hw01

### PR DESCRIPTION
**Pull request by leahvf**
I split this project into three phases. On day one I set up my GitHub and RStudio accounts and read over the links, "Mastering Markdown" and "General Homework Workflow."  I then forked the homework (HW01) and cloned it into RStudio. Day 2, I went to Lab Hours and spoke to Deb to make sure that I understood exactly what I needed to do for the assignment. Finally, I formatted a page without text according to the "Mastering Markdown" rules and uploaded it to GitHub in order to see that everything was working well. After uploading my photo to my GitHub Repository, but I put the error message into Google in order to understand what was wrong. I needed to merge the changes on my GitHub Repository with my version on RStudio - since the RStudio version I was working on had been cloned before adding the photo to GitHub. I did a pull, then had to push it, merging the two versions.  I then added the text and played around with the elements I had included previously.

When I first read over how to do this assignment I was very overwhelmed. Then I just tried to go step by step, reading all the links in order to understand what to do. Going into Lab Hours helped me to clear up misunderstandings. I think it will be important to get started with my weekly assignments as soon as possible in order to give myself time to make mistakes.

### CODE REVIEW

**Comment by yiranouyang** [comment]
Topic | Excellent | Satisfactory | Needs Work
-- | -- | -- | --
Coding style | x |   |  
Coding strategy | x |   |  
Presentation | x |   |  
Achievement, creativity | x |   |  
Ease of access | x |   |  

## Remarks
You did a **great** job of using the markdown language to produce various levels of headings, bold, italics, image, link, and bullet points. The biography has a neat format. I am curious to know the reason why you added the .jpeg picture into your repo? You also explained your three-step homework process and the problems you solved with great details. Thank you for sharing your work process.

**Comment by cscrivner** [comment]
Evaluation
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |      x     |              |            |
| **Coding strategy**         |           |      x        |            |
| **Presentation**            |      x     |              |            |
| **Achievement, creativity** |           |       x       |            |
| **Ease of access**          |        x   |              |            |

Remarks:
Nice job on HW1. Your readme is succinct and easy to to read. It does look like you might have uploaded the photo to GitHub rather than pushing it from Rstudio. One way to do this is simply put the photo in the same folder that you are working from. Then it should get pushed to GitHub along with the code.

**Comment by RSFlores** [comment]
Great job! Your readme includes over four of the required components: headings, bold, italics, bullet point, image, and a link.  The format is concise and clean. As others have noted, the picture should be pushed from your RStudio shell rather than put directly in your repo. Your comments on how you handled issues that came up on your workflow were also detailed and informative.

**Comment by pthelen124** [comment]
Evaluation
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |  x         |              |            |
| **Coding strategy**         |           |  x            |            |
| **Presentation**            |  x         |              |            |
| **Achievement, creativity** |           |  x            |            |
| **Ease of access**          |   x        |              |            |

Remarks:

* I think you did a great job here! Your code works and you've got all of the pieces needed for the assignment. Good work. 
* I like how you put the *LinkedIn* site in the middle of your sentence. It gives that statement an uninterrupted flow, and allows the reader to access the link if they'd like to. 
* It was pretty smart to split up the *personal* and *professional* aspects of your README. Keeps things well organized. 
* Your photo's caption doesn't appear to show up. I honestly can't figure out why this would be the case.  
* I agree that the assignment initially was overwhelming. I also found that meeting with the TAs and taking _**a lot**_ of time to figure out the elements needed to complete the assignment, as well as to troubleshoot, was a good idea. 

Great job!

**Pull request closed without merging**
