### PR TITLE
Jin Deng hw01

### PR DESCRIPTION
**Pull request by jin-deng**
**My workflow:**
1. Install GitHub following instructions https://cfss.uchicago.edu/setup/
2. Register my GitHub username for the course
3. Fork hw01 to my GitHub 
4. Pull from GitHub, create the repository in RStudio (New Project - Version Control - Git - Paste the Url - choose local directory)
5. Make changes locally to README.md in RStudio, refer https://guides.github.com/features/mastering-markdown/ for writing markdown documents, preview the output before committing it to GitHub
6. When I finish editing README.md, save it, commit my changes to my repo, push the commit to GitHub
7. Pull request to the Class GitHub page. Write down my workflow and problems 

**Problems I have solved:**
1. I did not know how to pull from GitHub in the beginning. I tried myself and checked with Deb. Deb corrected me that I needed to fork the hw01 rather than course site. 
2. I had trouble when I added lists to README.md. The lists did not show up when I previewed my codes. Then I found I used “**” rather than “*” in the guide. I switched to “*” and it worked. To create a sub list, I need at least 2 spaces before “*”.
3. I aslo had problems when I added links for my picture. I wanted my picture to direct the reader to a restaurant website when they click the picture. Then I googled for solutions. I needed to bracket my picture link [] and add a bracketed website link after it.

**Reflections:**
1. I found the most difficult part is setting up GitHub, understanding and practicing the GitHub workflow. It took me a while. But once I got it, it would be easy the next time.
2. I understood how to write markdown documents in a nice format. I find it is important to create a nice formatted output. Even though I have used markdown before, I did not pay much attention to the format. This homework helps a lot.

### CODE REVIEW

**Comment by jin-deng** [comment]
Please look at my final version. Thank you!

**Review by onjas-6 — COMMENTED** [review]
Hi! I'm Qitian Hu (Jason) reviewing your work.

I think it's great. It incorporates all the required elements, and your picture loads well (which is kinda rare among the ones I see). Also, thank you for recommending restaurants!

It's hard for me to give suggestions. Your style is great. I have a different habit when using bulletpoints: I don't add ":" after the higher-ranked bullets, because I think its status already infer the meaning of ":" However, it's personal preference, and you can choose whatever way you like.

**Comment by cscrivner** [comment]
Evaluation
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |     x      |              |            |
| **Coding strategy**         |          |       x       |            |
| **Presentation**            |      x     |              |            |
| **Achievement, creativity** |       x    |              |            |
| **Ease of access**          |      x     |              |            |

Remarks:

Nice job! I'll have to try the restaurants you mentioned. And well done making the picture of the sushi link to the website. My only comment would be to try and make your commit messages more informative.

**Review by JiaxiLi1995 — CHANGES_REQUESTED** [review]
Evaluation
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |       x    |              |            |
| **Coding strategy**         |      x     |              |            |
| **Presentation**            |       x    |              |            |
| **Achievement, creativity** |    x       |              |            |
| **Ease of access**          |    x       |              |            |

Remarks:

* Elaborate on above, especially for "needs work."
This is a great brief introduction.

* Some specific praise?
The descriptions of workflow and reflection are specific and through.

* Something I learned?
The sublist is interesting and new for me.

* Something I know and that you, my peer, might like to know because it is relevant to something you struggled with.
Setting up the git in R is really hard.

**Comment by ashleylee0228** [comment]
Evaluation
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |     x      |              |            |
| **Coding strategy**         |           |       x       |            |
| **Presentation**            |      x     |              |            |
| **Achievement, creativity** |     x      |              |            |
| **Ease of access**          |     x      |              |            |

Comments:
- Good coding style, presentation, achievement/ creativity, and ease of access. I appreciate your effort in adding so many photos! They were very aesthetic. 

- I liked the detail in your reflections; I also had similar problems for the first assignment (especially setting up the GitHub and getting used to the GitHub workflow!)

- I think you can improve your coding strategy by making your commits a bit more specific than "introduction" and "final version," so that you can track what changes you've made.

**Pull request closed without merging**
