### PR TITLE
Allison Whiting's Homework 1

### PR DESCRIPTION
**Pull request by whitingam**
I had a hard time getting started with R and Git, especially getting them to work together. However, working with Markdown was quite simple, and I don't anticipate having problems in the future.

To make my changes, I forked the file from the class page to my page, then I cloned and downloaded it into my R Studio, then I made the changes and committed it, and then finally I pushed it to GitHub. I had to repeat this process several times because I didn't get it right the first few.

### CODE REVIEW

**Comment by whitingam** [comment]
I had a hard time getting started with R and Git, especially getting them to work together.  However, working with Markdown was quite simple, and I don't anticipate having problems in the future.

To make my changes, I forked the file from the class page to my page, then I cloned and downloaded it into my R Studio, then I made the changes and committed it, and then finally I pushed it to GitHub.  I had to repeat this process several times because I didn't get it right the first few.

**Comment by cscrivner** [comment]
Evaluation
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |      x     |              |            |
| **Coding strategy**         |      x     |              |            |
| **Presentation**            |           |      x        |            |
| **Achievement, creativity** |           |      x        |            |
| **Ease of access**          |      x     |              |            |

Remarks:
Nice job on the HW. Don't be afraid to spice it up / try some new stuff in the homework. Glad you see the benefit in R, even as a qual researcher!

**Comment by yeonjang** [comment]
Evaluation
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |     x      |              |            |
| **Coding strategy**         |     x      |              |            |
| **Presentation**            |     x      |              |            |
| **Achievement, creativity** |           |       x       |            |
| **Ease of access**          |     x      |              |            |

Remarks:

* Elaborate on above, especially for "needs work."  
Code is efficient and clean, no errors; it runs well. Only thing, it could use just a little more creativity. 
* Some specific praise?  
Concise and easy to follow. Well organized. 
* Specific constructive criticism?  
Perhaps a touch too concise, could use more tools.

**Comment by HebaAlex** [comment]
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |   x        |              |            |
| **Coding strategy**         |   x        |              |            |
| **Presentation**            |   x      |              |            |
| **Achievement, creativity** |           |   x           |            |
| **Ease of access**          |     x      |              |            |

**Comment by nathanielsher** [comment]
| Topic                                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**                    |      X          |                       |                    |
| **Coding strategy**              |      X          |                       |                     |
| **Presentation**                    |                   |        X            |                     |
| **Achievement, creativity**  |                   |        X            |                     |
| **Ease of access**                |      X           |                       |                     |

Remarks: You completed all of the requirements for this assignmeny by including a header, list, link, and bold text. Nicely done. Perhaps a more detailed bio would have been spiced up the presentation.

**Comment by ashleylee0228** [comment]
Evaluation
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |     x      |              |            |
| **Coding strategy**         |     x      |              |            |
| **Presentation**            |           |       x       |            |
| **Achievement, creativity** |           |      x        |            |
| **Ease of access**          |     x      |              |            |

Comments:

- Satisfies the minimum we needed to do for the assignment (4 of 5 elements), but for better presentation and creativity, adding a photo might have been nice

- Good coding style/strategy; code runs well

- I had a bit trouble following your "commit" comments. Having more concise commit comments might be easier to track the changes you've made

**Pull request closed without merging**
