### PR TITLE
Katie Furrow HW 1

### PR DESCRIPTION
**Pull request by kfurrow**
To make the changes to the README file for HW 1, I first forked the repo, cloned it onto my computer, and then made the changes to the file in RStudio. While forking and cloning was a simple process (with the help of Google), I was initially fairly confused about where and how to make the changes because the online resources for how to work in Markdown weren't completely clear. I ended up making it far more difficult than it needed to be by trying to edit it through the terminal and the console. Through trial and error (and Deb's confirmation that I was doing it right), I was able to figure out that making the changes happened directly in the README in RStudio. 

The GitHub "Mastering Markdown" page provided the most help in figuring out how to properly format the page.

### CODE REVIEW

**Comment by cscrivner** [comment]
Evaluation
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |           |        x      |            |
| **Coding strategy**         |           |      x        |            |
| **Presentation**            |      x     |              |            |
| **Achievement, creativity** |      x     |              |            |
| **Ease of access**          |      x     |              |            |

Remarks:
Well done on HW1. It looks like you might have uploaded some stuff directly to GitHub (rather than pushing). Perhaps the image? If so, in the future, just put the image in the same folder on your computer as the code you're working on and it will be pushed up tp Github along with the code. If this wasn't the case, then you can ignore that. And if you you'd like to put a title for an image, you can just put that in a line above the code for inserting the image. 

As a side note, I also love Nathan Pyle's alien comics and despise cilantro

**Comment by luijosie** [comment]
Evaluation
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |           |        X      |            |
| **Coding strategy**         |     X      |              |            |
| **Presentation**            |      X     |              |            |
| **Achievement, creativity** |     X      |              |            |
| **Ease of access**          |    X       |              |            |

Remarks:
Your presentation is clear and concise. You made good use of elements of markdown syntax to make information tidy. Your reflection on the process is well explained. I think you can also explore sublists :)

**Review by emezra — COMMENTED** [review]
Evaluation
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |         |      x        |            |
| **Coding strategy**         |    x      |              |            |
| **Presentation**            |          |              |      x      |
| **Achievement, creativity** |           |      x        |            |
| **Ease of access**          |          |              |     x       |

Remarks:

This might be just me, but I'm having a lot of trouble accessing the markdown biography. I'm only seeing just code, and not the final knitted version of your document. The code itself is good, but I can't see the final document the way I think I'm supposed to.

**Comment by dmukkamala** [comment]
Evaluation
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |        X   |              |            |
| **Coding strategy**         |           |        X      |            |
| **Presentation**            |         X  |              |            |
| **Achievement, creativity** |      X     |              |            |
| **Ease of access**          |      X     |              |            |

Great job on Homework 1. You hit on all of the necessary features and more. I found the comic particularly enjoyable. One possible change that I would consider is using underscores to repeat bolds or italics; I found it easier than asterisks. To your point on the difficulty of using R Markdown, I found the cheat sheet to be quite useful.

**Comment by katrinaturickuchicago** [comment]
Evaluation
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |      x     |              |            |
| **Coding strategy**         |      x     |              |            |
| **Presentation**            |      x     |              |            |
| **Achievement, creativity** |      x     |              |            |
| **Ease of access**          |     x      |              |            |

Remarks:

* Your bio looks great! I love those comics.
* The comment given above about properly loading the image and adding a title were helpful for me too, I also had a problem with that.
* Also search for R Markdown cheat sheet online if you want more in the future - I found it more helpful than Github's page!

**Pull request closed without merging**
