### PR TITLE
Elizabeth Huppert Hw01 Submission

### PR DESCRIPTION
**Pull request by ehuppert**
To complete this homework assignment, I forked the master repository into my own repository, and I used the pull command to download the assignment into my R console. I use R relatively frequently so I felt comfortable typing and working in the R console, but Git and Github are brand new to me. I found the process of getting the assignment from Git into R a little bit confusing at first, but it was not too hard to navigate. I mainly ran into trouble when trying to push my completed changes (the assignment) back to Github. After saving and committing, I tried to "push" and I received an error when pushing, despite the fact that I could see the assignment on my Github page. After consulting with Deb, it seemed that all is working, but I am a little confused still on what happened to spit out that error message in the push process earlier. Additionally, I realized that I had to commit and push my image itself (not just the image code) to my Github page to make the image display. I feel a little more confident with Git than I did earlier this week, but I am still shaky on the integration of Git/Github and R itself.

### CODE REVIEW

**Comment by mmdeng1** [comment]
Topic | Excellent | Satisfactory | Needs Work
-- | -- | -- | --
Coding style | x |   |  
Coding strategy | x |   |  
Presentation | x |   |  
Achievement, creativity | x |   |  
Ease of access | x |   |  

Hi Elizabeth, your brief biography absolutely looks amazing. I like the first table you put at the very front, it gives a succinct but meaningful illustration of the date, author and assignment series. I will try the same table for my next assignment too. In general, I think you have tried every basic requirements: bold, italic, links, images, and you have well put them together. I would suggest to make a short list of your background to make it more organized, but it truly looks good by far.
One thing I am not so sure about is the last section of your table, I am just a bit curious why you put output there. But in general, you did a great job.

**Comment by cscrivner** [comment]
Evaluation
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |       x    |              |            |
| **Coding strategy**         |     x      |              |            |
| **Presentation**            |       x    |              |            |
| **Achievement, creativity** |      x     |              |            |
| **Ease of access**          |      x     |              |            |

Remarks:

Well done on the first assignment. You went beyond the minimum requirements to make your readme more substantive. I didn't realize you worked in Jean's lab. I'm friends with some of the folks in his lab (E.g., Mika Armenta and Savannah Yerman). I'm also TAing for Jean this quarter.

**Comment by onjas-6** [comment]
Evaluation
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |           |     x         |            |
| **Coding strategy**         |       x    |              |            |
| **Presentation**            |      x     |              |            |
| **Achievement, creativity** |      x     |              |            |
| **Ease of access**          |     x      |              |            |

Remarks:

* I really like your work, you goes far beyond the minimum requirement of trying only a few syntax, but used nearly every syntax mentioned.
* but it would be better if you could be more frequent in terms of saving your work. 
* I learned to be more specific in the pull request reflection.

**Comment by katrinaturickuchicago** [comment]
Evaluation
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |      x     |              |            |
| **Coding strategy**         |     x      |              |            |
| **Presentation**            |     x      |              |            |
| **Achievement, creativity** |     x      |              |            |
| **Ease of access**          |      x     |              |            |

Remarks:

* Everything displayed well! You used a lot of the formatting options which made it look great.
* Interesting bio, I liked hearing about your research, since I also do psychology research!
* I also found the integration of github and R a little confusing, and the [homework flow](https://cfss.uchicago.edu/faq/homework-guidelines/#homework-workflow) diagram on the website helped me, in case you haven't seen it.

**Pull request closed without merging**
