### PR TITLE
ClairePotterHomework1

### PR DESCRIPTION
**Pull request by claireanastasia**
I used the "General Homework Guidelines" as a guide to fork the repository for Homework 1, and then clone the repository onto my computer by taking the URL from GitHub and pasting it into the "repository URL" space of my new project in RStudio. Then, I used the Markdown cheatsheet from GitHub that Professor Soltoff provided a link to in order to write my bio and to make sure that I included headers, italics, bold, lists, an image, and a link. Everything seemed to be going smoothly and I liked the way my bio looked in GitStudio's preview, so I committed my work to my repo and then pushed the commit to GitHub. Here I ran into a problem. The photo that showed up in the preview on RStudio wasn't displaying on GitHub. I tried rewriting the code for the image a view times and adding a caption. Each time I made a change I thought might work, I committed the changes and pushed the commit to GitHub. Finally, renaming the photo's file name so that it had no spaces worked.

### CODE REVIEW

**Comment by cscrivner** [comment]
Evaluation
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |      x     |              |            |
| **Coding strategy**         |    x       |              |            |
| **Presentation**            |          |       x      |            |
| **Achievement, creativity** |    x      |              |            |
| **Ease of access**          |    x       |              |            |

Remarks:

Nice job on the first assignment. Everything looks good, and you even included an extra element. And yes, spaces are tricky. Best to just use underscores or dashes for file names. Well done!

**Review by ZManta — COMMENTED** [review]
Evaluation
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |     x      |              |            |
| **Coding strategy**         |     x      |              |            |
| **Presentation**            |    x       |              |            |
| **Achievement, creativity** |     x      |              |            |
| **Ease of access**          |           |      x        |            |

Remarks:

* Elaborate on above, especially for "needs work."
Looks great! Only thing I would add is that I think you don't need to commit and pull request the other little files that get created, like gitignore.
* Some specific praise?
Your nested lists look great, and good job getting the picture to work.
* Something I learned?
Nested lists like a champ
* Specific constructive criticism?
I see that you tried to add a caption on the photo but I don't see it showing up, I'm not sure why.
* Something I know and that you, my peer, might like to know because it is relevant to something you struggled with.
Pull quotes are a fun bonus, as you saw! Just use >
-Zach

**Comment by pthelen124** [comment]
Evaluation
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |  x         |              |            |
| **Coding strategy**         |  x         |              |            |
| **Presentation**            |  x         |              |            |
| **Achievement, creativity** |  x         |              |            |
| **Ease of access**          |   x        |              |            |

Remarks:

* I think you did a great job here! Your code works, you've got all of the pieces needed for the assignment, with an extra even. Good work. 
* I like that you italicized all of the titles for both books and movies. It gives the nested list a more authentic feel than had they been plain text.
* Your "bullets/numbers" in your list were cool. I used the default bullet points, but I hadn't thought to make Roman numeral lists. Innovative. 
* Your photo's caption doesn't appear to show up. I honestly can't figure out why this would be the case.  
* It doesn't seem like you struggled with much, given your comment. I would say that (as you've already learned), using underscores, dashes, or periods between the words in a filename can help with keeping the workflow running smoothly. 

Great job!

**Comment by pthelen124** [comment]
Evaluation
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |  x         |              |            |
| **Coding strategy**         |  x         |              |            |
| **Presentation**            |  x         |              |            |
| **Achievement, creativity** |  x         |              |            |
| **Ease of access**          |   x        |              |            |

Remarks:

* I think you did a great job here! Your code works, you've got all of the pieces needed for the assignment, with an extra even. Good work. 
* I like that you italicized all of the titles for both books and movies. It gives the nested list a more authentic feel than had they been plain text.
* Your "bullets/numbers" in your list were cool. I used the default bullet points, but I hadn't thought to make Roman numeral lists. Innovative. 
* Your photo's caption doesn't appear to show up. I honestly can't figure out why this would be the case.  
* It doesn't seem like you struggled with much, given your comment. I would say that (as you've already learned), using underscores, dashes, or periods between the words in a filename can help with keeping the workflow running smoothly. 

Great job!

**Comment by pthelen124** [comment]
Evaluation
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |  x         |              |            |
| **Coding strategy**         |  x         |              |            |
| **Presentation**            |  x         |              |            |
| **Achievement, creativity** |  x         |              |            |
| **Ease of access**          |   x        |              |            |

Remarks:

* I think you did a great job here! Your code works, you've got all of the pieces needed for the assignment, with an extra even. Good work. 
* I like that you italicized all of the titles for both books and movies. It gives the nested list a more authentic feel than had they been plain text.
* Your "bullets/numbers" in your list were cool. I used the default bullet points, but I hadn't thought to make Roman numeral lists. Innovative. 
* Your photo's caption doesn't appear to show up. I honestly can't figure out why this would be the case.  
* It doesn't seem like you struggled with much, given your comment. I would say that (as you've already learned), using underscores, dashes, or periods between the words in a filename can help with keeping the workflow running smoothly. 

Great job!

**Comment by pthelen124** [comment]
Evaluation
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |  x         |              |            |
| **Coding strategy**         |  x         |              |            |
| **Presentation**            |  x         |              |            |
| **Achievement, creativity** |  x         |              |            |
| **Ease of access**          |   x        |              |            |

Remarks:

* I think you did a great job here! Your code works, you've got all of the pieces needed for the assignment, with an extra even. Good work. 
* I like that you italicized all of the titles for both books and movies. It gives the nested list a more authentic feel than had they been plain text.
* Your "bullets/numbers" in your list were cool. I used the default bullet points, but I hadn't thought to make Roman numeral lists. Innovative. 
* Your photo's caption doesn't appear to show up. I honestly can't figure out why this would be the case.  
* It doesn't seem like you struggled with much, given your comment. I would say that (as you've already learned), using underscores, dashes, or periods between the words in a filename can help with keeping the workflow running smoothly. 

Great job!

**Comment by nathanielsher** [comment]
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |      X     |              |            |
| **Coding strategy**         |     X      |              |            |
| **Presentation**            |      X     |              |            |
| **Achievement, creativity** |      X     |              |            |
| **Ease of access**          |   X        |              |            |

Remarks: You completed all of the requirements for this assignment by including headers, bold text, italics, a link, and an image. Your presentation was well organized with lists and sublists. Nice work on troubleshooting your image issue. Well done!

**Pull request closed without merging**
