### PR TITLE
Nathaniel Sher hw01

### PR DESCRIPTION
**Pull request by nathanielsher**
I managed to get through this assignment with only a few hiccups. First, resizing my image proved to be difficult. I attempted to make my image smaller with this code < div style="width:50px; height:50px" >. This worked in RMarkdown, showing a successfully minimized image in the preview; however, when pushed to Github, it only printed the code for the image. In general, moving between RStudio and GitHub was the most difficult part of this assignment. I have yet to fully internalize the logic of the homework workflow, but after doing this a few more times I hope it will become second nature. Other than that, formatting in RMarkdown was relatively easy.

### CODE REVIEW

**Review by clairebrainard — COMMENTED** [review]
Evaluation
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |     x      |              |            |
| **Coding strategy**         |     x      |              |            |
| **Presentation**            |           |           x   |            |
| **Achievement, creativity** |           |      x        |            |
| **Ease of access**          |     x      |              |            |

Remarks:
Overall, really good! Hit all the requirements for the assignment. You mentioned on how you had trouble getting the photo to be sized right. I did notice it was quite large. Maybe tinkering with it some more would have gotten the result you were going for. The other individuals homework I did my peer evaluation on figured out how to resize her photo through googling it. It was interesting to hear about your brief time-line of your life. I thought it was funny. Nice job!

**Review by JinghanZhu — COMMENTED** [review]
Evaluation
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |     ☑️      |              |            |
| **Coding strategy**         |     ☑️      |              |            |
| **Presentation**            |     ☑️      |              |            |
| **Achievement, creativity** |     ☑️      |              |            |
| **Ease of access**          |      ☑️     |              |            |

Remarks:

* You met all of the requirements for the assignment, including headings, italicized text, links, and images.
* Your article is a good read!
* As a reader, it would be great to learn a bit more about you as a person other than "learned to walk and learned to speak".

**Review by bensoltoff — COMMENTED** [review]
Evaluation
----------------------------------------------------
| Topic                       | Excellent | Satisfactory | Needs Work |
|-----------------------------|-----------|--------------|------------|
| **Coding style**            |   x        |              |            |
| **Coding strategy**         |    x       |              |            |
| **Presentation**            |      x     |              |            |
| **Achievement, creativity** |   x        |              |            |
| **Ease of access**          |       x    |              |            |

Remarks:

* Good addition of a photo to the repo for publication
* You have a long commit history. In the future, try to leave a more informative message each time explaining the purpose of the commit
* To prevent people from running malicious code on their website, GitHub will not render HTML code written in Markdown `.md` files. This is why you could not resize the image the way you wanted to. In RStudio, when you previewed the document the resize probably worked because RStudio does not have the same protections in place. To make it appear the size you want on GitHub, easiest approach is to manually change the size of the image and save the smaller version for embedding

**Comment by bensoltoff** [comment]
I take that back. See your peer's submission #20. If you use an HTML tag like

```
<img src="http://district29pto.org/wp-content/uploads/2018/09/thankyou.jpg" length= "280" width="257">
```

the resize works. There might be some exceptions to GitHub's restrictions on HTML code in Markdown documents.

**Pull request closed without merging**
